### ISSUE TITLE
Clicking on the already selected value should close the menu

### ISSUE THREAD

**Issue by kungufli** [PolymerElements/paper-dropdown-menu#72]
When you click (or tap) on the item that it's already the selected one the user probably expect the menu to close, like in the native html `<select>`. Instead the `paper-dropdown-menu` does nothing and you are forced to click outside of the menu to close it without changing the selected value.

**Comment by miztroh** [comment]
+1

**Comment by Mipme** [comment]
+1

**Comment by Silvercast** [comment]
+1

**Comment by kungufli** [comment]
Fixed in the last version. Thanks

**Comment by freshp86** [comment]
I can still reproduce this when using real Shadow DOM, by doing `Polymer.dom = 'shadow';`

Can we re-open?

**Comment by addyosmani** [comment]
@freshp86 do you have a test case where you're using native SD and this fails that we can take a look at?

**Comment by freshp86** [comment]
The easiest way to reproduce is to add the following lines 
```
<script>
    window.Polymer = window.Polymer || {};
    window.Polymer.dom = 'shadow';
  </script>
```

right after https://github.com/PolymerElements/paper-dropdown-menu/blob/master/demo/index.html#L18.

**Comment by freshp86** [comment]
@addyosmani: Where you able to reproduce?

**Comment by freshp86** [comment]
@cdata: FYI, I found a candidate fix for this, see https://github.com/freshp86/iron-selector/commit/8fd9a0cc0f881f2afe3c58a1a930543f1cf4b355. I am hoping that a better fix exists, but at least this PR reveals where the problem lies.

**Comment by freshp86** [comment]
@tjsavage This is affecting Chrome's new Polymer settings,(https://code.google.com/p/chromium/issues/detail?id=425627)

**Comment by cdata** [comment]
This reproduces for me on http://polygit.org/components/paper-dropdown-menu/demo/index.html?dom=shadow

**Comment by bicknellr** [comment]
I think the problem is with paper-menu-button: it closes on 'iron-select' (when a new selection is made) rather than 'iron-activate' (when an item is clicked).

**Comment by cdata** [comment]
@bicknellr Correct, although this decision is by design. `iron-activate` is not a suitable event because it corresponds with a specifically configured mode of user input.

**Comment by bicknellr** [comment]
Hmm, I get the feeling there's something lost between what the two events represent. It makes sense that `iron-activate` doesn't necessarily close the menu because there could be controls in the menu that activate without causing a selection (opening nested menus), but it also seems wrong that an actual selection change firing `iron-select` is the only thing that could close the menu.

**Comment by cdata** [comment]
@bicknellr It seems that there may be a feature that could be added to `paper-listbox` to enable the desired outcome. Consider a new strawman property: `discardSelection`. This causes any selection to a `listbox` to be immediately deselected after it has been selected. The semantics when this property is set to true might be:

 1. The `iron-select` event fires when a selection is made
 2. The state of the selection is somehow maintained by `paper-dropdown-menu` (et al)
 3. The `paper-listbox` immediately deselects the value after the selection is made

**Comment by freshp86** [comment]
/cc @danbeam
Any updates on this?

Regarding the proposal of automatically deselecting, sounds a bit odd (at least if it happens by default). How about either of the following approaches?

1. Pass a parameter (HTML attribute?) to paper-menu and paper-listbox, that instructs them to always fire an event even if the same menu item is clicked. Then paper-dropdown-menu would catch that event and close hide itself.
2. Always fire the iron-select event and include "oldValue" and "newValue" in the event payload. In the case where the same value was clicked then oldValue === newValue. Callers who care only about a change would need to check whether the value change and return early if it did not.

**Comment by Stefdv** [comment]
+1 on @danbeam

**Comment by valdrinkoshi** [comment]
You can also listen to `tap` event on the `paper-listbox` and close the menu http://jsbin.com/fasagi/1/edit?html,output

**Comment by freshp86** [comment]
@valdrinkoshi: Thanks for the workaround suggestion.

I still think that Polymer elements that have a 1:1 correspondence with native elements (in this case <select>), should strive to behave as close as possible. Clicking on the already selected option within a <select> closes the menu. Having to apply the workaround on every paper-dropdown-menu instance is sub-optimal, compared to having it be the default behavior.

**Comment by valdrinkoshi** [comment]
I agree that the right component should take care of this; in particular, this should be taken care by `paper-menu-button`, since it is the one responsible of the closing of the dropdown when the selection changes (there is already an issue there https://github.com/PolymerElements/paper-menu-button/issues/85)
About the 1:1 correspondence with `<select>`, I disagree, because `paper-dropdown-menu` (and `paper-menu-button` that is used internally) can virtually contain any other element as their children, while `select` deals only with `<option>` :)

**Comment by bicknellr** [comment]
Fixed in #168.
